Todolist review
arslanbisharat/to-do-list pull request #1
Opened 2020-07-05 09:19 UTC by arslanbisharat

This is the 4th project of the Main Javascript curriculum at [Microverse](https://www.microverse.org/) - @microverseinc

* The objective is to build a page with interactivity using everything learn about **Objects**, **Factory Functions**, The **Module Pattern**
* The project was completed using Javascript language.

>**note** I completed this project

2020-07-06 04:18 UTC, arslanbisharat commented
### note
Thank you for  reviewing my project i kept default value high

2020-07-06 13:59 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi there @arslanbisharat 
How are you?
Nice job so far :clap: :clap: 
We only need to make some changes before moving on :smile: 

- [x] The stickler file was added but it seems you forgot to set up the linter here on Github. We need to fix that and allow the linter to verify your repo in the PR. Check the instructions [here](https://github.com/microverseinc/linters-config/tree/master/javascript) 

- [x] Your eslint file is different from the one [provided](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json) from Microverse. We need to fix that.

- [x] I noticed that your package.json file has no scripts defined. We need to add at least 2 scripts, development, and production and properly inform how Webpack should run in each one of them. Check my comment below.

- [x] The README file needs to have information on how the user can download and test your app locally. This instruction is related to the scripts available at the package file. 

- [x]  The user should be able to edit the details of a to-do item, like title and description.

Please kindly submit for code review again after making these changes.

Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**
[Twitter](https://twitter.com/torres_ssf) [LinkedIn](https://www.linkedin.com/in/torres-ssf/) [Portifolio](https://www.torres-ssf.com/)

2020-07-06 13:59 UTC, Torres-ssf commented on package.json
> +  },
- [ ] We need to use at least 2 scripts here, one for development and another one for production. Each one should inform in each mode Webpack should run (development and production).

2020-07-07 18:34 UTC, fatymahmed requested changes
## Hi @arslanbisharat 
Great job fixing most of the suggested changes 👏👏, however, a few things need to be fixed
- [ ] Set up linter and make sure it passes the check 
- [ ] The user should be able to edit a `todo's` details, I can't edit the `title` of the `todo` [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png)
## Status: Changes Required ♻️

2020-07-07 19:40 UTC, arslanbisharat commented
@fatymahmed  @Torres-ssf  I can easily change any information by double clickingon it

2020-07-07 21:28 UTC, Redvanisation approved these changes
# Approved ✔️ 

### Hello team 🌟 

### _Nice work on this project, it seems that you have met the requirements. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

2020-07-07 21:30 UTC, merged